language: python
script: true
deploy:
  provider: pypi
  username: __token__
  password:
    secure: $PYPI_KEY
  distributions: sdist bdist_wheel
  on:
    tags: true
  edge: true
  skip_existing: true
