blank_issues_enabled: false
contact_links:
  - name: Leek5 Support server (Only in Korean!)
    url: https://leek.pcor.me/support.php
    about: Pycord-components' official discord server (you can get help here!)
